################################# Default configuration ###################
# provide your domain here
baseURL = "https://7dtd.suzu.me.uk/"
# theme
theme = "dot"
# site title
title = "7dtd.SUZU.ME.uk"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "UA-198220-17" # paste your analytics ID here. (Ex: UA-123-45)

defaultContentLanguage = "ja"

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################

[[menu.main]]
name = "ルール"
url = "rules"
weight = 1

[[menu.main]]
name = "特徴"
url = "features/"
weight = 1

[[menu.main]]
name = "Faq"
url = "faq"
weight = 2 

#[[menu.main]]
#name = "contact"
#url = "contact"
#weight = 2

## Dropdown menu
#[[menu.main]]
#weight = 3
#name = "docs"
#hasChildren = true
#
#  [[menu.main]]
#  parent = "docs"
#  name = "Installation"
#  url = "installation"
#  weight = 1
#
#  [[menu.main]]
#  parent = "docs"
#  name = "Billing and Pricing"
#  url = "billing-pricing"
#  weight = 2
#
#  [[menu.main]]
#  parent = "docs"
#  name = "Features"
#  url = "features"
#  weight = 3


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

################################### Japanese Language ######################
[Languages.ja]
languageName = "Ja"
languageCode = "ja-jp"
weight = 1
home = "ホーム"
copyright = "The 7dtd suzume server are copyright © [7dtd.SUZU.ME.uk](https://7dtd.suzu.me.uk/) 2020."

# banner
[Languages.ja.params.banner]
title = "7dtd PVE SUZUME server"
subtitle = "7 days to die PVE すずめサーバーにようこそ"
bg_image = "images/banner.jpg"
placeholder = ""

# call to action
[Languages.ja.params.cta]
enable = false
title = "質問に対する答えが見つかりませんでしたか?"
content = ""
# call to action button
[Languages.ja.params.cta.button]
enable = false
label = "contact us"
link = "contact"

################################# English Language ######################
#[Languages.en]
#languageName = "En"
#languageCode = "en-us"
#weight = 2
#home = "Home"
#copyright = "The 7dtd suzume server are copyright © [7dtd.SUZU.ME.uk](https://7dtd.suzu.me.uk/) 2020."
#
## banner
#[Languages.en.params.banner]
#title = "7dtd SUZUME server"
#subtitle = "WELCOME TO 7dtd SUZUME server"
#bg_image = "images/banner.jpg"
#placeholder = ""
#
## call to action
#[Languages.en.params.cta]
#enable = false
#title = "Didn't find an answer to your question?"
#content = ""
## call to action button
#[Languages.en.params.cta.button]
#enable = false
#label = "contact us"
#link = "contact"
#
#
